### ISSUE TITLE
Market Research - Similar packages

### ISSUE THREAD

**Issue by elabandari** [UBC-MDS/pyhousehunter#2]
Hey folks,

I found a python [craigslist scraper package](https://github.com/narfman0/craigslist-scraper), however, this package has minimal functionality (i.e. doesn't take in user input and doesn't email results). Our package definitely meets the market gap based on our proposed functions.

Assigning @elina-linglin to this issue as this is part of the README.md.

Best,
Ela

**Comment by elabandari** [comment]
This is another impressive craigslist scraper (https://github.com/juliomalegria/python-craigslist) but it doesn't have emailing functionality and isn't solely focused on housing.

**Comment by JuntingHe** [comment]
Hi team,
I found an R package to get data from craigslist https://github.com/adletaw/craigr. It can obtain data from any section of craigslist and load it into a clean data.frame within R.

**Comment by elina-linglin** [comment]
Thank you folks for the researching! I will incorporate these into our README file.
