### ISSUE TITLE
Function 2: Cleaner 

### ISSUE THREAD

**Issue by elabandari** [UBC-MDS/pyhousehunter#4]

**Comment by elabandari** [comment]
This function was changed from a user-input function into a data cleaning function given that the data scraped from the web is not very clean.

**Comment by JuntingHe** [comment]
Function 2 takes in the scraped **dataframe** scarping from Function 1 and returns a cleaned **dataframe** object containing ininformation like listing url, price, number of bedroom, area in sqft, and city and ready for filtering.

**Comment by JuntingHe** [comment]
This  function will use Pandas and Regex to clean the scraped data.

**Comment by JuntingHe** [comment]
Reopen the issue and move it to milestone2

**Comment by JuntingHe** [comment]
### Ideas/notes that are related to the cleaner function .
- convert **the price** column into numerice data types
- extract the information about **the number of bedroom of the housing**  and **the area of the housing** from the house_type column
- extract the information about which **city** are the housing located in from the listing_url column
- select the columns (listing url, price, number of bedroom, area in sqft, and city) which are useful for future filtering
